"""helloWeb QA tests — auto-generated by QA Agent on each PR.

此檔案由 QA Agent 在每次 PR 時自動覆蓋，不需手動維護。
"""
import pathlib


def test_normal_index_exists():
    """index.html 必須存在。"""
    html_path = pathlib.Path(__file__).resolve().parent / "index.html"
    assert html_path.exists(), "index.html not found"


def test_edge_greeting_present():
    """index.html 必須含問候文字。"""
    html_path = pathlib.Path(__file__).resolve().parent / "index.html"
    content = html_path.read_text(encoding="utf-8")
    assert "楊政憲" in content, "Greeting not found in index.html"
